project_name: goval-dictionary
release:
  github:
    owner: kotakanbe
    name: goval-dictionary
builds:
- goos:
  - linux
  goarch:
  - amd64
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.revision={{.Commit}}
  binary: goval-dictionary
archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  files:
  - LICENSE
  - README*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
